AAP_HOSTNAME=localhost
AAP_VALIDATE_CERTS=false
AAP_ORGANIZATION_NAME=foo
AAP_PROJECT_NAME=bar
AAP_PROJECT_GIT_URI=https://github.com/innabox/cloudkit-aap
AAP_PROJECT_GIT_BRANCH=main
AAP_EE_IMAGE=quay.io/rh-ee-jkary/cloudkit-aap-ee
LICENSE_MANIFEST_PATH=/var/secrets/config-as-code-manifest/license.zip

