apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  # The name of the resource is 'cluster'
  name: cluster
  # The annotations section contains the key-value pair
  annotations:
    ingress.operator.openshift.io/default-enable-http2: 'true'
