---
apiVersion: v1
kind: Secret
metadata:
  name: quay-pull-secret
  namespace: cloudkit
  labels:
    app.kubernetes.io/name: cloudkit
    app.kubernetes.io/managed-by: kustomize
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "quay.io": {
          "auth": "placeholder"
        }
      }
    } 