---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
  namespace: cloudkit
  labels:
    app.kubernetes.io/name: cloudkit-operator
    app.kubernetes.io/managed-by: kustomize
data:
  zap-config.yaml: |
    level: info
    development: false
    sampling:
      initial: 100
      thereafter: 100
    outputPaths:
      - stdout
    errorOutputPaths:
      - stderr
    encoderConfig:
      messageKey: message
      levelKey: level
      timeKey: time
      callerKey: caller
      stacktraceKey: stacktrace
      lineEnding: ""
      levelEncoder: lowercase
      timeEncoder: iso8601
      durationEncoder: seconds
      callerEncoder: short
      nameEncoder: ""
    initialFields:
      service: cloudkit-operator
