---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: cloudkit
  labels:
    app.kubernetes.io/name: cloudkit-operator
    app.kubernetes.io/managed-by: kustomize
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        image: quay.io/innabox/cloudkit-operator
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "cloudkit-operator"
        - name: CONFIG_PATH
          value: "/etc/config/controller_manager_config.yaml"
        - name: FEATURE_GATES_PATH
          value: "/etc/feature-gates/feature-gates.yaml"
        - name: LOGGING_CONFIG_PATH
          value: "/etc/logging/zap-config.yaml"
        - name: WEBHOOK_CONFIG_PATH
          value: "/etc/webhook/webhook-config.yaml"
        volumeMounts:
        - name: manager-config
          mountPath: /etc/config
          readOnly: true
        - name: feature-gates
          mountPath: /etc/feature-gates
          readOnly: true
        - name: logging-config
          mountPath: /etc/logging
          readOnly: true
        - name: webhook-config
          mountPath: /etc/webhook
          readOnly: true
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: quay-pull-secret
      volumes:
      - name: manager-config
        configMap:
          name: manager-config
      - name: feature-gates
        configMap:
          name: feature-gates
      - name: logging-config
        configMap:
          name: logging-config
      - name: webhook-config
        configMap:
          name: webhook-config 
