---
apiVersion: cloudkit.io/v1alpha1
kind: CloudKit
metadata:
  name: sample-cloudkit
  namespace: default
  labels:
    app.kubernetes.io/name: cloudkit-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  size: 3
  image: "quay.io/innabox/cloudkit:latest"
  storage:
    size: "10Gi"
    storageClassName: "fast-ssd"
  resources:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "256Mi"
