apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudkit-development-unified

# Development environment annotations
commonAnnotations:
  environment: development

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    environment: development

# Include base resources (cloudkit-aap, cloudkit-operator, shared)
resources:
- ../../base/shared
- ./cloudkit-aap
- ./cloudkit-operator
- ./fulfillment-service

# Images are now configured in base directories

namespace: foobar
namePrefix: dev-

# Secret generators for both components
secretGenerator:
- files:
  - .dockerconfigjson=dockerconfig.json
  name: quay-pull-secret
  type: kubernetes.io/dockerconfigjson
  options:
    disableNameSuffixHash: true
