apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fulfillment-api
  labels:
    app: fulfillment-service
    component: service
spec:
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: dev-fulfillment-api
    weight: 100
  port:
    targetPort: api
