---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudkit-sa
  namespace: cloudkit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudkit-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cloudkit-aap-cloudkit-sa
    namespace: cloudkit
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-fulfillment-ig
  namespace: cloudkit
type: Opaque
stringData:
  credentials: |
    # Setup here the credentials required for cluster fulfillment playbooks (AWS, OpenStack, ...)

