---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudkit-sa
  namespace: cloudkit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudkit-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cloudkit-aap-cloudkit-sa
    namespace: cloudkit
---
#
# We cannot create the secret for AAP becuase it will then
# be prevented from adding the real password value when deploying.
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudkit-admin-password
#   namespace: cloudkit
# type: Opaque
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudkit-eda-admin-password
#   namespace: cloudkit
# type: Opaque
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: config-as-code-ig
#   namespace: cloudkit
# type: Opaque
# data:
#   vars.yaml: ""
# Don't want this because secretGenerator takes care of it.
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: bar-config-as-code-manifest-ig
#   namespace: cloudkit
# type: Opaque
# data:
#   license.zip: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-fulfillment-ig
  namespace: cloudkit
type: Opaque
stringData:
  credentials: |
    # Setup here the credentials required for cluster fulfillment playbooks (AWS, OpenStack, ...)

