apiVersion: batch/v1
kind: Job
metadata:
  name: aap-bootstrap
  namespace: cloudkit
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-aap
        image: registry.redhat.io/ubi8/ubi-minimal:latest
        command:
          - /bin/sh
          - -c
          - |
            echo "Waiting for AAP controller to be ready..."
            microdnf install -y curl
            for i in $(seq 1 30); do
              echo "Attempt $i/30: Checking AAP controller readiness..."
              if curl -skf ${AAP_GATEWAY_URL}/api/gateway/v1/ping/ | grep -q 'good'; 
              then
                echo "AAP controller is ready!"
                exit 0
              fi
              echo "Controller not ready, waiting 600 seconds..."
              sleep 600
            done
            echo "Timeout waiting for AAP controller"
            exit 1
        env:
        - name: AAP_GATEWAY_URL
          value: ""
      containers:
      - image: quay.io/rh-ee-jkary/cloudkit-aap-ee:latest
        name: bootstrap
        args:
        - ansible-playbook
        - cloudkit.config_as_code.subscription
        - cloudkit.config_as_code.configure
        envFrom:
        - secretRef:
            name: config-as-code-ig
        env:
        - name: AAP_USERNAME
          value: admin
        - name: AAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-cloudkit-admin-password
              key: password
        - name: AAP_EDA_USERNAME
          value: admin
        - name: AAP_EDA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-cloudkit-eda-admin-password
              key: password
        volumeMounts:
        - name: config-as-code-manifest-volume
          mountPath: /var/secrets/config-as-code-manifest
          readOnly: true
      volumes:
      - name: config-as-code-manifest-volume
        secret:
          secretName: bar-config-as-code-manifest-ig
      imagePullSecrets:
      - name: quay-pull-secret
      restartPolicy: Never
  backoffLimit: 4
